KBUILD_CFLAGS += -Wlarger-than=57584

obj-$(CONFIG_AMLOGIC_STREAMING)	+=	common/
obj-$(CONFIG_AMLOGIC_STREAMING)	+=	frame_provider/
obj-$(CONFIG_AMLOGIC_STREAMING)	+=	frame_sink/
obj-$(CONFIG_AMLOGIC_STREAMING)	+=	stream_input/
