obj-$(CONFIG_AMLOGIC_STREAMING)	+= aml_hardware_fe.o

ccflags-$(CONFIG_AMLOGIC_STREAMING) += -I$(srctree)/drivers/media/dvb-core -I$(srctree)/drivers/gpio -I$(srctree)/include

aml_hardware_fe-objs += aml_fe.o

